// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqDxNpqij-4V6p_UJ615XgAC5j2xAibp4',
    appId: '1:707432048304:web:your-web-app-id',
    messagingSenderId: '707432048304',
    projectId: 'musicshare-adfe8',
    authDomain: 'musicshare-adfe8.firebaseapp.com',
    storageBucket: 'musicshare-adfe8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqDxNpqij-4V6p_UJ615XgAC5j2xAibp4',
    appId: '1:707432048304:android:cec14c6d64303f893efd75',
    messagingSenderId: '707432048304',
    projectId: 'musicshare-adfe8',
    storageBucket: 'musicshare-adfe8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqDxNpqij-4V6p_UJ615XgAC5j2xAibp4',
    appId: '1:707432048304:ios:your-ios-app-id',
    messagingSenderId: '707432048304',
    projectId: 'musicshare-adfe8',
    storageBucket: 'musicshare-adfe8.firebasestorage.app',
    iosBundleId: 'com.musicshare.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqDxNpqij-4V6p_UJ615XgAC5j2xAibp4',
    appId: '1:707432048304:ios:your-macos-app-id',
    messagingSenderId: '707432048304',
    projectId: 'musicshare-adfe8',
    storageBucket: 'musicshare-adfe8.firebasestorage.app',
    iosBundleId: 'com.musicshare.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqDxNpqij-4V6p_UJ615XgAC5j2xAibp4',
    appId: '1:707432048304:web:your-windows-app-id',
    messagingSenderId: '707432048304',
    projectId: 'musicshare-adfe8',
    authDomain: 'musicshare-adfe8.firebaseapp.com',
    storageBucket: 'musicshare-adfe8.firebasestorage.app',
  );
}
